
swagger: '2.0'
info:
  title:  Bank Argent API documentation
  description: Contains all available API endpoints in this codebase 
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:8000
basePath: /api/v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /user/transactions/{id}:
    delete:
      summary: delete transaction
      description: API for Transaction delete 
      parameters:
        - name: id
          in: path
          description: ID of the transaction
          required: true
          schema:
           type: number
      produces:
        - application/json
      responses:
        '200':
          description: delete Transaction Successfully
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
         
  /user/inventory/{id}:
    patch:
      summary: user inventory
      parameters:
        - name: id
          in: path
          description: ID of the inventory
          required: true
          schema:
           type: number
        - in: body
          name: body
          description: Update user inventory Payload
          required: true
          schema:
            type: object
            $ref: '#/definitions/InventoryUpdateBody'
      responses:
       '200':
          description: updated Successfully
          schema:
            $ref: '#/definitions/InventoryUpdateBody'
       '400':
          description: Invalid Fields
       '500':
          description: Internal Server Error
  /user/transactions/{id}:
    patch:
      summary: update single transaction
      parameters:
        - name: id
          in: path
          description: ID of the user
          required: true
          schema:
           type: number
        - in: body
          name: body
          description: Updated transaction Payload
          required: true
          schema:
            type: object
            $ref: '#/definitions/TransactionUpdateBody'
      responses:
       '200':
          description: updated Successfully
          schema:
            $ref: '#/definitions/TransactionUpdateBody'
       '400':
          description: Invalid Fields
       '500':
          description: Internal Server Error
  /user/transactions:
    get:
      summary: Get all transactions
      responses:
        '200':
          description: OK
  /user/inventories:
    get:
      summary: Get all inventories
      responses:
        '200':
          description: OK
  /user/transaction/{id}:
    get:
      summary: Get single transaction
      parameters:
        - name: id
          in: path
          description: ID of the user
          required: true
          schema:
           type: number
      responses:
       '200':
          description: single transaction fetched Successfully
          schema:
            $ref: '#/definitions/TransactionBody'
       '400':
          description: Invalid Fields
       '500':
          description: Internal Server Error
  /user/transaction:
    post:
      summary: Post a transaction
      parameters:
        - in: body
          name: body
          description: Transaction Payload
          required: true
          schema:
            $ref: '#/definitions/TransactionBody'
      produces:
        - application/json
      responses:
        '200':
          description: transaction posted Successfully
          schema:
            $ref: '#/definitions/TransactionBody'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
definitions:
    TransactionBody:
      properties:
        id:
          type: number
          description: transaction id
        date:
          type: string
          description: transaction date
        amount:
          type: number
          description: transaction amount
        balance:
          type: number
          description: transaction balance
    TransactionUpdateBody:
      properties:
        date:
          type: string
          description: transaction date
        amount:
          type: number
          description: transaction amount
        balance:
          type: number
          description: transaction balance
    InventoryUpdateBody: 
      properties:
        type:
          type: string
          description: transaction type
        category:
          type: string
          description: category
        notes:
          type: string
          description: notes       



# swagger: '2.0'
# info:
#   title: Bank Argent API documentation
#   description: Contains all available API endpoints in this codebase
#   version: '1.0.0'
#   termsOfService: 'http://swagger.io/terms/'
# host: localhost:3001
# basePath: /api/v1
# schemes:
#   - http
# paths:
#   /user/login:
#     post:
#       tags:
#         - User Module
#       summary: Login
#       description: API for Login
#       parameters:
#         - in: body
#           name: body
#           description: Login Payload
#           required: true
#           schema:
#             $ref: '#/definitions/Login'
#       produces:
#         - application/json
#       responses:
#         '200':
#           description: Login Successfully
#           schema:
#             $ref: '#/definitions/LoginResponse'
#         '400':
#           description: Invalid Fields
#         '500':
#           description: Internal Server Error
#   /user/signup:
#     post:
#       tags:
#         - User Module
#       summary: Signup
#       description: API for Signup
#       parameters:
#         - in: body
#           name: body
#           description: Signup Payload
#           required: true
#           schema:
#             $ref: '#/definitions/User'
#       produces:
#         - application/json
#       responses:
#         '200':
#           description: Signup Successfully
#           schema:
#             $ref: '#/definitions/ApiResponse'
#         '400':
#           description: Invalid Fields
#         '500':
#           description: Internal Server Error
#   /user/profile:
#     post:
#       security:
#         - Bearer: []
#       tags:
#         - User Module
#       summary: User Profile API
#       description: API for fetching a user profile
#       parameters:
#         - in: header
#           name: Authorization
#           description: Attach Bearer JWT token
#           required: true
#       produces:
#         - application/json
#       responses:
#         '200':
#           description: User profile retrieved successully
#           schema:
#             $ref: '#/definitions/ApiResponse'
#         '400':
#           description: Invalid Fields
#         '500':
#           description: Internal Server Error
#     put:
#       security:
#         - Bearer: []
#       tags:
#         - User Module
#       summary: User Profile API
#       description: API for updating a user profile
#       parameters:
#         - in: header
#           name: Authorization
#           description: Attach Bearer JWT token
#           required: true
#         - in: body
#           name: body
#           description: Update user profile attributes
#           required: true
#           schema:
#             $ref: '#/definitions/UserProfile'
#       produces:
#         - application/json
#       responses:
#         '200':
#           description: User profile retrieved successully
#           schema:
#             $ref: '#/definitions/ApiResponse'
#         '400':
#           description: Invalid Fields
#         '500':
#           description: Internal Server Error
# securityDefinitions:
#   Bearer:
#     type: apiKey
#     name: Authorization
#     in: header
# definitions:
#   User:
#     properties:
#       email:
#         type: string
#         description: user email
#       password:
#         type: string
#         description: user password
#       firstName:
#         type: string
#         description: user first name
#       lastName:
#         type: string
#         description: user last name
#   Login:
#     properties:
#       email:
#         type: string
#         description: user email
#       password:
#         type: string
#         description: user password
#   ApiResponse:
#     type: object
#     properties:
#       status:
#         type: integer
#       message:
#         type: string
#       body:
#         type: object
#         properties:
#           id:
#             type: string
#           email:
#             type: string
#   LoginResponse:
#     type: object
#     properties:
#       token:
#         type: string
#   UserProfile:
#     type: object
#     properties:
#       firstName:
#         type: string
#       lastName:
#         type: string
